// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: envelope.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

/// Persistence envelopes for Workspace definitions and preferences.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The persistence envelope for a WorkspaceDefinition. Contains an external_id
/// and a concrete WorkspaceDefinition.
public nonisolated struct Ldtx_Envelope_WorkspaceDefinitionEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The UUIDv7 identifier for this persisted document.
  public var externalID: String = String()

  public var definition: Ldtx_Envelope_WorkspaceDefinitionEnvelope.OneOf_Definition? = nil

  /// The Version 4 WorkspaceDefinition.
  public var workspaceDefinitionV4: Ldtx_Workspace_V4_WorkspaceDefinitionV4 {
    get {
      if case .workspaceDefinitionV4(let v)? = definition {return v}
      return Ldtx_Workspace_V4_WorkspaceDefinitionV4()
    }
    set {definition = .workspaceDefinitionV4(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    /// The Version 4 WorkspaceDefinition.
    case workspaceDefinitionV4(Ldtx_Workspace_V4_WorkspaceDefinitionV4)

  }

  public init() {}
}

/// The persistence envelope for WorkspacePreferences. Contains an external_id
/// and a concrete WorkspacePreferences.
public nonisolated struct Ldtx_Envelope_WorkspacePreferencesEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The UUIDv7 identifier for this persisted document.
  public var externalID: String = String()

  public var preferences: Ldtx_Envelope_WorkspacePreferencesEnvelope.OneOf_Preferences? = nil

  /// The Version 4 WorkspacePreferences.
  public var workspacePreferencesV4: Ldtx_Workspace_V4_WorkspacePreferencesV4 {
    get {
      if case .workspacePreferencesV4(let v)? = preferences {return v}
      return Ldtx_Workspace_V4_WorkspacePreferencesV4()
    }
    set {preferences = .workspacePreferencesV4(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Preferences: Equatable, Sendable {
    /// The Version 4 WorkspacePreferences.
    case workspacePreferencesV4(Ldtx_Workspace_V4_WorkspacePreferencesV4)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.envelope"

nonisolated extension Ldtx_Envelope_WorkspaceDefinitionEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WorkspaceDefinitionEnvelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}external_id\0\u{3}workspace_definition_v4\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.externalID) }()
      case 2: try {
        var v: Ldtx_Workspace_V4_WorkspaceDefinitionV4?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .workspaceDefinitionV4(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .workspaceDefinitionV4(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.externalID.isEmpty {
      try visitor.visitSingularStringField(value: self.externalID, fieldNumber: 1)
    }
    try { if case .workspaceDefinitionV4(let v)? = self.definition {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Envelope_WorkspaceDefinitionEnvelope, rhs: Ldtx_Envelope_WorkspaceDefinitionEnvelope) -> Bool {
    if lhs.externalID != rhs.externalID {return false}
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Envelope_WorkspacePreferencesEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WorkspacePreferencesEnvelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}external_id\0\u{3}workspace_preferences_v4\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.externalID) }()
      case 2: try {
        var v: Ldtx_Workspace_V4_WorkspacePreferencesV4?
        var hadOneofValue = false
        if let current = self.preferences {
          hadOneofValue = true
          if case .workspacePreferencesV4(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.preferences = .workspacePreferencesV4(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.externalID.isEmpty {
      try visitor.visitSingularStringField(value: self.externalID, fieldNumber: 1)
    }
    try { if case .workspacePreferencesV4(let v)? = self.preferences {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Envelope_WorkspacePreferencesEnvelope, rhs: Ldtx_Envelope_WorkspacePreferencesEnvelope) -> Bool {
    if lhs.externalID != rhs.externalID {return false}
    if lhs.preferences != rhs.preferences {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
