// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace_v4_preferences.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

/// Version 4 Workspace mutable preferences.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Contains mutable preferences for one WorkspaceDefinitionV4.
public nonisolated struct Ldtx_Workspace_V4_WorkspacePreferencesV4: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Mutable preferences for Programs in this Workspace, keyed by Program
  /// internal_id.
  public var programPreferences: Dictionary<UInt64,Ldtx_Workspace_V4_ProgramPreference> = [:]

  /// The Workspace-wide monitor volume in decibels.
  public var monitorVolume: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Contains mutable preferences for one Program.
public nonisolated struct Ldtx_Workspace_V4_ProgramPreference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Landscape audio gain in decibels for each Audio Input Device, keyed by
  /// Input Device internal_id.
  public var landscapeAudioChannelGains: Dictionary<UInt64,Double> = [:]

  /// Whether each Landscape Audio Input Device is muted, keyed by Input Device
  /// internal_id.
  public var landscapeAudioChannelMuted: Dictionary<UInt64,Bool> = [:]

  /// The transforms for Landscape Video Layers, keyed by Video Input Device or
  /// Video Component internal_id.
  public var landscapeVideoLayerTransforms: Dictionary<UInt64,Ldtx_Workspace_V4_BasicTransform> = [:]

  /// Whether each Landscape Video Layer is muted, keyed by Video Input Device
  /// or Video Component internal_id.
  public var landscapeVideoLayerMuted: Dictionary<UInt64,Bool> = [:]

  /// The Portrait audio gain in decibels for each Audio Input Device, keyed by
  /// Input Device internal_id.
  public var portraitAudioChannelGains: Dictionary<UInt64,Double> = [:]

  /// Whether each Portrait Audio Input Device is muted, keyed by Input Device
  /// internal_id.
  public var portraitAudioChannelMuted: Dictionary<UInt64,Bool> = [:]

  /// The transforms for Portrait Video Layers, keyed by Video Input Device or
  /// Video Component internal_id.
  public var portraitVideoLayerTransforms: Dictionary<UInt64,Ldtx_Workspace_V4_BasicTransform> = [:]

  /// Whether each Portrait Video Layer is muted, keyed by Video Input Device or
  /// Video Component internal_id.
  public var portraitVideoLayerMuted: Dictionary<UInt64,Bool> = [:]

  /// The Landscape master volume in decibels.
  public var landscapeMasterVolume: Double = 0

  /// The Portrait master volume in decibels.
  public var portraitMasterVolume: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The basic transform applied to a Video Layer, which is a Video Input Device
/// or a Video Component.
public nonisolated struct Ldtx_Workspace_V4_BasicTransform: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The horizontal translation in coordinates normalized to the Canvas that
  /// renders this Video Layer, in the range [0, 1].
  public var translationX: Float = 0

  /// The vertical translation in coordinates normalized to the Canvas that
  /// renders this Video Layer, in the range [0, 1].
  public var translationY: Float = 0

  /// The horizontal scale.
  public var scaleX: Float = 0

  /// The vertical scale.
  public var scaleY: Float = 0

  /// The top inset as a fraction of this Video Layer's statically defined
  /// content height, in the range [0, 1].
  public var topInset: Float = 0

  /// The right inset as a fraction of this Video Layer's statically defined
  /// content width, in the range [0, 1].
  public var rightInset: Float = 0

  /// The bottom inset as a fraction of this Video Layer's statically defined
  /// content height, in the range [0, 1].
  public var bottomInset: Float = 0

  /// The left inset as a fraction of this Video Layer's statically defined
  /// content width, in the range [0, 1].
  public var leftInset: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v4"

nonisolated extension Ldtx_Workspace_V4_WorkspacePreferencesV4: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WorkspacePreferencesV4"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}program_preferences\0\u{3}monitor_volume\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_ProgramPreference>.self, value: &self.programPreferences) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.monitorVolume) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.programPreferences.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_ProgramPreference>.self, value: self.programPreferences, fieldNumber: 1)
    }
    if self.monitorVolume.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.monitorVolume, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_WorkspacePreferencesV4, rhs: Ldtx_Workspace_V4_WorkspacePreferencesV4) -> Bool {
    if lhs.programPreferences != rhs.programPreferences {return false}
    if lhs.monitorVolume != rhs.monitorVolume {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_ProgramPreference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramPreference"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}landscape_audio_channel_gains\0\u{3}landscape_audio_channel_muted\0\u{3}landscape_video_layer_transforms\0\u{3}landscape_video_layer_muted\0\u{3}portrait_audio_channel_gains\0\u{3}portrait_audio_channel_muted\0\u{3}portrait_video_layer_transforms\0\u{3}portrait_video_layer_muted\0\u{3}landscape_master_volume\0\u{3}portrait_master_volume\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufDouble>.self, value: &self.landscapeAudioChannelGains) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: &self.landscapeAudioChannelMuted) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_BasicTransform>.self, value: &self.landscapeVideoLayerTransforms) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: &self.landscapeVideoLayerMuted) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufDouble>.self, value: &self.portraitAudioChannelGains) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: &self.portraitAudioChannelMuted) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_BasicTransform>.self, value: &self.portraitVideoLayerTransforms) }()
      case 8: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: &self.portraitVideoLayerMuted) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self.landscapeMasterVolume) }()
      case 10: try { try decoder.decodeSingularDoubleField(value: &self.portraitMasterVolume) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.landscapeAudioChannelGains.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufDouble>.self, value: self.landscapeAudioChannelGains, fieldNumber: 1)
    }
    if !self.landscapeAudioChannelMuted.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: self.landscapeAudioChannelMuted, fieldNumber: 2)
    }
    if !self.landscapeVideoLayerTransforms.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_BasicTransform>.self, value: self.landscapeVideoLayerTransforms, fieldNumber: 3)
    }
    if !self.landscapeVideoLayerMuted.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: self.landscapeVideoLayerMuted, fieldNumber: 4)
    }
    if !self.portraitAudioChannelGains.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufDouble>.self, value: self.portraitAudioChannelGains, fieldNumber: 5)
    }
    if !self.portraitAudioChannelMuted.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: self.portraitAudioChannelMuted, fieldNumber: 6)
    }
    if !self.portraitVideoLayerTransforms.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_BasicTransform>.self, value: self.portraitVideoLayerTransforms, fieldNumber: 7)
    }
    if !self.portraitVideoLayerMuted.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: self.portraitVideoLayerMuted, fieldNumber: 8)
    }
    if self.landscapeMasterVolume.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.landscapeMasterVolume, fieldNumber: 9)
    }
    if self.portraitMasterVolume.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.portraitMasterVolume, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_ProgramPreference, rhs: Ldtx_Workspace_V4_ProgramPreference) -> Bool {
    if lhs.landscapeAudioChannelGains != rhs.landscapeAudioChannelGains {return false}
    if lhs.landscapeAudioChannelMuted != rhs.landscapeAudioChannelMuted {return false}
    if lhs.landscapeVideoLayerTransforms != rhs.landscapeVideoLayerTransforms {return false}
    if lhs.landscapeVideoLayerMuted != rhs.landscapeVideoLayerMuted {return false}
    if lhs.portraitAudioChannelGains != rhs.portraitAudioChannelGains {return false}
    if lhs.portraitAudioChannelMuted != rhs.portraitAudioChannelMuted {return false}
    if lhs.portraitVideoLayerTransforms != rhs.portraitVideoLayerTransforms {return false}
    if lhs.portraitVideoLayerMuted != rhs.portraitVideoLayerMuted {return false}
    if lhs.landscapeMasterVolume != rhs.landscapeMasterVolume {return false}
    if lhs.portraitMasterVolume != rhs.portraitMasterVolume {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_BasicTransform: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BasicTransform"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}translation_x\0\u{3}translation_y\0\u{3}scale_x\0\u{3}scale_y\0\u{3}top_inset\0\u{3}right_inset\0\u{3}bottom_inset\0\u{3}left_inset\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.translationX) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.translationY) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.scaleX) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.scaleY) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.topInset) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.rightInset) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self.bottomInset) }()
      case 8: try { try decoder.decodeSingularFloatField(value: &self.leftInset) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.translationX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.translationX, fieldNumber: 1)
    }
    if self.translationY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.translationY, fieldNumber: 2)
    }
    if self.scaleX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.scaleX, fieldNumber: 3)
    }
    if self.scaleY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.scaleY, fieldNumber: 4)
    }
    if self.topInset.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.topInset, fieldNumber: 5)
    }
    if self.rightInset.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.rightInset, fieldNumber: 6)
    }
    if self.bottomInset.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.bottomInset, fieldNumber: 7)
    }
    if self.leftInset.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.leftInset, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_BasicTransform, rhs: Ldtx_Workspace_V4_BasicTransform) -> Bool {
    if lhs.translationX != rhs.translationX {return false}
    if lhs.translationY != rhs.translationY {return false}
    if lhs.scaleX != rhs.scaleX {return false}
    if lhs.scaleY != rhs.scaleY {return false}
    if lhs.topInset != rhs.topInset {return false}
    if lhs.rightInset != rhs.rightInset {return false}
    if lhs.bottomInset != rhs.bottomInset {return false}
    if lhs.leftInset != rhs.leftInset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
