// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace_v4_vision.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

/// Version 4 Workspace Vision definitions.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Wraps one concrete Vision definition.
public nonisolated struct Ldtx_Workspace_V4_VisionWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var definition: Ldtx_Workspace_V4_VisionWrapper.OneOf_Definition? = nil

  /// The OCR Vision definition. Mutually exclusive with the other fields.
  public var ocrVision: Ldtx_Workspace_V4_OcrVision {
    get {
      if case .ocrVision(let v)? = definition {return v}
      return Ldtx_Workspace_V4_OcrVision()
    }
    set {definition = .ocrVision(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    /// The OCR Vision definition. Mutually exclusive with the other fields.
    case ocrVision(Ldtx_Workspace_V4_OcrVision)

  }

  public init() {}
}

/// A normalized rectangle in the input image. Its origin is relative to the
/// lower-left corner.
public nonisolated struct Ldtx_Workspace_V4_VisionRegionOfInterest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The horizontal origin, in the range [0, 1].
  public var x: Float = 0

  /// The vertical origin, in the range [0, 1].
  public var y: Float = 0

  /// The width, in the range [0, 1].
  public var width: Float = 0

  /// The height, in the range [0, 1].
  public var height: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Wraps one concrete Vision trigger definition.
public nonisolated struct Ldtx_Workspace_V4_VisionTriggerWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var definition: Ldtx_Workspace_V4_VisionTriggerWrapper.OneOf_Definition? = nil

  /// The interval-based Vision trigger definition. Mutually exclusive with
  /// the other fields.
  public var intervalTrigger: Ldtx_Workspace_V4_IntervalVisionTrigger {
    get {
      if case .intervalTrigger(let v)? = definition {return v}
      return Ldtx_Workspace_V4_IntervalVisionTrigger()
    }
    set {definition = .intervalTrigger(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    /// The interval-based Vision trigger definition. Mutually exclusive with
    /// the other fields.
    case intervalTrigger(Ldtx_Workspace_V4_IntervalVisionTrigger)

  }

  public init() {}
}

/// A Vision trigger that invokes Vision at a regular interval.
public nonisolated struct Ldtx_Workspace_V4_IntervalVisionTrigger: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The interval between automatic Vision updates in seconds.
  public var intervalSeconds: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// An image-analysis request that recognizes text in an image.
public nonisolated struct Ldtx_Workspace_V4_OcrVision: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Vision shown in the Workspace sidebar.
  public var displayName: String = String()

  /// The conditions that automatically trigger this Vision.
  public var triggers: [Ldtx_Workspace_V4_VisionTriggerWrapper] = []

  public var source: Ldtx_Workspace_V4_OcrVision.OneOf_Source? = nil

  /// Uses this Input Device as input.
  public var inputDeviceInternalID: UInt64 {
    get {
      if case .inputDeviceInternalID(let v)? = source {return v}
      return 0
    }
    set {source = .inputDeviceInternalID(newValue)}
  }

  /// The region of the input image in which Vision performs the request.
  public var regionOfInterest: Ldtx_Workspace_V4_VisionRegionOfInterest {
    get {_regionOfInterest ?? Ldtx_Workspace_V4_VisionRegionOfInterest()}
    set {_regionOfInterest = newValue}
  }
  /// Returns true if `regionOfInterest` has been explicitly set.
  public var hasRegionOfInterest: Bool {self._regionOfInterest != nil}
  /// Clears the value of `regionOfInterest`. Subsequent reads from it will return its default value.
  public mutating func clearRegionOfInterest() {self._regionOfInterest = nil}

  /// Whether text recognition prioritizes accuracy over speed. False uses the
  /// fast level.
  public var accurate: Bool = false

  /// The BCP 47 languages Vision detects, in priority order. An empty list
  /// enables automatic language detection.
  public var recognitionLanguages: [String] = []

  /// Whether Vision applies language correction during text recognition.
  public var usesLanguageCorrection: Bool = false

  /// The words that supplement Vision's lexicon during word recognition.
  /// Vision uses these only when language correction is enabled.
  public var customWords: [String] = []

  /// The minimum text height relative to input image height. When absent, the
  /// Vision Framework default applies.
  public var minimumTextHeight: Float {
    get {_minimumTextHeight ?? 0}
    set {_minimumTextHeight = newValue}
  }
  /// Returns true if `minimumTextHeight` has been explicitly set.
  public var hasMinimumTextHeight: Bool {self._minimumTextHeight != nil}
  /// Clears the value of `minimumTextHeight`. Subsequent reads from it will return its default value.
  public mutating func clearMinimumTextHeight() {self._minimumTextHeight = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Source: Equatable, Sendable {
    /// Uses this Input Device as input.
    case inputDeviceInternalID(UInt64)

  }

  public init() {}

  fileprivate var _regionOfInterest: Ldtx_Workspace_V4_VisionRegionOfInterest? = nil
  fileprivate var _minimumTextHeight: Float? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v4"

nonisolated extension Ldtx_Workspace_V4_VisionWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VisionWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}ocr_vision\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Ldtx_Workspace_V4_OcrVision?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .ocrVision(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .ocrVision(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .ocrVision(let v)? = self.definition {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_VisionWrapper, rhs: Ldtx_Workspace_V4_VisionWrapper) -> Bool {
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_VisionRegionOfInterest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VisionRegionOfInterest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.width) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    if self.width.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.width, fieldNumber: 3)
    }
    if self.height.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.height, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_VisionRegionOfInterest, rhs: Ldtx_Workspace_V4_VisionRegionOfInterest) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_VisionTriggerWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VisionTriggerWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}interval_trigger\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Ldtx_Workspace_V4_IntervalVisionTrigger?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .intervalTrigger(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .intervalTrigger(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .intervalTrigger(let v)? = self.definition {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_VisionTriggerWrapper, rhs: Ldtx_Workspace_V4_VisionTriggerWrapper) -> Bool {
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_IntervalVisionTrigger: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IntervalVisionTrigger"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}interval_seconds\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.intervalSeconds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.intervalSeconds.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.intervalSeconds, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_IntervalVisionTrigger, rhs: Ldtx_Workspace_V4_IntervalVisionTrigger) -> Bool {
    if lhs.intervalSeconds != rhs.intervalSeconds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_OcrVision: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OcrVision"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0\u{1}triggers\0\u{3}input_device_internal_id\0\u{3}region_of_interest\0\u{1}accurate\0\u{3}recognition_languages\0\u{3}uses_language_correction\0\u{3}custom_words\0\u{3}minimum_text_height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.triggers) }()
      case 4: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.source != nil {try decoder.handleConflictingOneOf()}
          self.source = .inputDeviceInternalID(v)
        }
      }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._regionOfInterest) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.accurate) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.recognitionLanguages) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.usesLanguageCorrection) }()
      case 9: try { try decoder.decodeRepeatedStringField(value: &self.customWords) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self._minimumTextHeight) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if !self.triggers.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.triggers, fieldNumber: 3)
    }
    try { if case .inputDeviceInternalID(let v)? = self.source {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._regionOfInterest {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.accurate != false {
      try visitor.visitSingularBoolField(value: self.accurate, fieldNumber: 6)
    }
    if !self.recognitionLanguages.isEmpty {
      try visitor.visitRepeatedStringField(value: self.recognitionLanguages, fieldNumber: 7)
    }
    if self.usesLanguageCorrection != false {
      try visitor.visitSingularBoolField(value: self.usesLanguageCorrection, fieldNumber: 8)
    }
    if !self.customWords.isEmpty {
      try visitor.visitRepeatedStringField(value: self.customWords, fieldNumber: 9)
    }
    try { if let v = self._minimumTextHeight {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_OcrVision, rhs: Ldtx_Workspace_V4_OcrVision) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.triggers != rhs.triggers {return false}
    if lhs.source != rhs.source {return false}
    if lhs._regionOfInterest != rhs._regionOfInterest {return false}
    if lhs.accurate != rhs.accurate {return false}
    if lhs.recognitionLanguages != rhs.recognitionLanguages {return false}
    if lhs.usesLanguageCorrection != rhs.usesLanguageCorrection {return false}
    if lhs.customWords != rhs.customWords {return false}
    if lhs._minimumTextHeight != rhs._minimumTextHeight {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
