// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace_v4_vfx.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

/// Version 4 Workspace Video Effect definitions.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Wraps one concrete Video Effect definition.
public nonisolated struct Ldtx_Workspace_V4_VideoEffectWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var definition: Ldtx_Workspace_V4_VideoEffectWrapper.OneOf_Definition? = nil

  /// The custom Video Effect definition. Mutually exclusive with the other
  /// fields.
  public var custom: Ldtx_Workspace_V4_CustomVideoEffect {
    get {
      if case .custom(let v)? = definition {return v}
      return Ldtx_Workspace_V4_CustomVideoEffect()
    }
    set {definition = .custom(newValue)}
  }

  /// The background-removal VFX effect definition. Mutually exclusive with
  /// the other fields.
  public var backgroundRemoval: Ldtx_Workspace_V4_BackgroundRemovalVfxEffect {
    get {
      if case .backgroundRemoval(let v)? = definition {return v}
      return Ldtx_Workspace_V4_BackgroundRemovalVfxEffect()
    }
    set {definition = .backgroundRemoval(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    /// The custom Video Effect definition. Mutually exclusive with the other
    /// fields.
    case custom(Ldtx_Workspace_V4_CustomVideoEffect)
    /// The background-removal VFX effect definition. Mutually exclusive with
    /// the other fields.
    case backgroundRemoval(Ldtx_Workspace_V4_BackgroundRemovalVfxEffect)

  }

  public init() {}
}

/// A customization point for a Video Effect.
public nonisolated struct Ldtx_Workspace_V4_CustomVideoEffect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The JSON representation of this custom Video Effect. Its format is
  /// unspecified.
  public var json: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A Video Effect that removes the background from input video.
public nonisolated struct Ldtx_Workspace_V4_BackgroundRemovalVfxEffect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The background-removal model to use.
  public var model: Ldtx_Workspace_V4_BackgroundRemovalVfxEffect.Model = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Model: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// No background-removal model is specified.
    case unspecified // = 0

    /// The MediaPipe landscape model.
    case mediapipeLandscape // = 1
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .mediapipeLandscape
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .mediapipeLandscape: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Ldtx_Workspace_V4_BackgroundRemovalVfxEffect.Model] = [
      .unspecified,
      .mediapipeLandscape,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v4"

nonisolated extension Ldtx_Workspace_V4_VideoEffectWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoEffectWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}custom\0\u{3}background_removal\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Ldtx_Workspace_V4_CustomVideoEffect?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .custom(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .custom(v)
        }
      }()
      case 2: try {
        var v: Ldtx_Workspace_V4_BackgroundRemovalVfxEffect?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .backgroundRemoval(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .backgroundRemoval(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.definition {
    case .custom?: try {
      guard case .custom(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .backgroundRemoval?: try {
      guard case .backgroundRemoval(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_VideoEffectWrapper, rhs: Ldtx_Workspace_V4_VideoEffectWrapper) -> Bool {
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_CustomVideoEffect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CustomVideoEffect"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}json\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.json) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.json.isEmpty {
      try visitor.visitSingularStringField(value: self.json, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_CustomVideoEffect, rhs: Ldtx_Workspace_V4_CustomVideoEffect) -> Bool {
    if lhs.json != rhs.json {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_BackgroundRemovalVfxEffect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BackgroundRemovalVfxEffect"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}model\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.model) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.model != .unspecified {
      try visitor.visitSingularEnumField(value: self.model, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_BackgroundRemovalVfxEffect, rhs: Ldtx_Workspace_V4_BackgroundRemovalVfxEffect) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_BackgroundRemovalVfxEffect.Model: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNSPECIFIED\0\u{1}MEDIAPIPE_LANDSCAPE\0")
}
