// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace_v4_video_component.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

/// Version 4 Workspace Video Component definitions.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Wraps one concrete Video Component definition.
public nonisolated struct Ldtx_Workspace_V4_VideoComponentWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var definition: Ldtx_Workspace_V4_VideoComponentWrapper.OneOf_Definition? = nil

  /// The solid-color fill Video Component definition. Mutually exclusive with
  /// the other fields.
  public var solidColorFill: Ldtx_Workspace_V4_FillSolidColorComponent {
    get {
      if case .solidColorFill(let v)? = definition {return v}
      return Ldtx_Workspace_V4_FillSolidColorComponent()
    }
    set {definition = .solidColorFill(newValue)}
  }

  /// The linear-gradient fill Video Component definition. Mutually exclusive
  /// with the other fields.
  public var linearGradientFill: Ldtx_Workspace_V4_FillLinearGradientComponent {
    get {
      if case .linearGradientFill(let v)? = definition {return v}
      return Ldtx_Workspace_V4_FillLinearGradientComponent()
    }
    set {definition = .linearGradientFill(newValue)}
  }

  /// The radial-gradient fill Video Component definition. Mutually exclusive
  /// with the other fields.
  public var radialGradientFill: Ldtx_Workspace_V4_FillRadialGradientComponent {
    get {
      if case .radialGradientFill(let v)? = definition {return v}
      return Ldtx_Workspace_V4_FillRadialGradientComponent()
    }
    set {definition = .radialGradientFill(newValue)}
  }

  /// The conic-gradient fill Video Component definition. Mutually exclusive
  /// with the other fields.
  public var conicGradientFill: Ldtx_Workspace_V4_FillConicGradientComponent {
    get {
      if case .conicGradientFill(let v)? = definition {return v}
      return Ldtx_Workspace_V4_FillConicGradientComponent()
    }
    set {definition = .conicGradientFill(newValue)}
  }

  /// The VFX Source Video Component definition. Mutually exclusive with the
  /// other fields.
  public var vfxSource: Ldtx_Workspace_V4_VfxSourceComponent {
    get {
      if case .vfxSource(let v)? = definition {return v}
      return Ldtx_Workspace_V4_VfxSourceComponent()
    }
    set {definition = .vfxSource(newValue)}
  }

  /// The clock Video Component definition. Mutually exclusive with the other
  /// fields.
  public var clock: Ldtx_Workspace_V4_ClockComponent {
    get {
      if case .clock(let v)? = definition {return v}
      return Ldtx_Workspace_V4_ClockComponent()
    }
    set {definition = .clock(newValue)}
  }

  /// The test-pattern Video Component definition. Mutually exclusive with the
  /// other fields.
  public var testPattern: Ldtx_Workspace_V4_TestPatternComponent {
    get {
      if case .testPattern(let v)? = definition {return v}
      return Ldtx_Workspace_V4_TestPatternComponent()
    }
    set {definition = .testPattern(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    /// The solid-color fill Video Component definition. Mutually exclusive with
    /// the other fields.
    case solidColorFill(Ldtx_Workspace_V4_FillSolidColorComponent)
    /// The linear-gradient fill Video Component definition. Mutually exclusive
    /// with the other fields.
    case linearGradientFill(Ldtx_Workspace_V4_FillLinearGradientComponent)
    /// The radial-gradient fill Video Component definition. Mutually exclusive
    /// with the other fields.
    case radialGradientFill(Ldtx_Workspace_V4_FillRadialGradientComponent)
    /// The conic-gradient fill Video Component definition. Mutually exclusive
    /// with the other fields.
    case conicGradientFill(Ldtx_Workspace_V4_FillConicGradientComponent)
    /// The VFX Source Video Component definition. Mutually exclusive with the
    /// other fields.
    case vfxSource(Ldtx_Workspace_V4_VfxSourceComponent)
    /// The clock Video Component definition. Mutually exclusive with the other
    /// fields.
    case clock(Ldtx_Workspace_V4_ClockComponent)
    /// The test-pattern Video Component definition. Mutually exclusive with the
    /// other fields.
    case testPattern(Ldtx_Workspace_V4_TestPatternComponent)

  }

  public init() {}
}

/// A Video Component that renders a CSS solid-color fill.
public nonisolated struct Ldtx_Workspace_V4_FillSolidColorComponent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Video Component shown in the Workspace sidebar.
  public var displayName: String = String()

  /// The color of this fill.
  public var color: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_color ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  public var hasColor: Bool {self._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  public mutating func clearColor() {self._color = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _color: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
}

/// A Video Component that renders a CSS linear-gradient fill.
public nonisolated struct Ldtx_Workspace_V4_FillLinearGradientComponent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Video Component shown in the Workspace sidebar.
  public var displayName: String = String()

  /// The horizontal coordinate of the gradient start point, expressed as a
  /// fraction of the width of the Canvas that renders this Fill, in [0, 1].
  public var startX: Float = 0

  /// The vertical coordinate of the gradient start point, expressed as a
  /// fraction of the height of the Canvas that renders this Fill, in [0, 1].
  public var startY: Float = 0

  /// The color at the gradient start point.
  public var startColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_startColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_startColor = newValue}
  }
  /// Returns true if `startColor` has been explicitly set.
  public var hasStartColor: Bool {self._startColor != nil}
  /// Clears the value of `startColor`. Subsequent reads from it will return its default value.
  public mutating func clearStartColor() {self._startColor = nil}

  /// The horizontal coordinate of the gradient end point, expressed as a
  /// fraction of the width of the Canvas that renders this Fill, in [0, 1].
  public var endX: Float = 0

  /// The vertical coordinate of the gradient end point, expressed as a
  /// fraction of the height of the Canvas that renders this Fill, in [0, 1].
  public var endY: Float = 0

  /// The color at the gradient end point.
  public var endColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_endColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_endColor = newValue}
  }
  /// Returns true if `endColor` has been explicitly set.
  public var hasEndColor: Bool {self._endColor != nil}
  /// Clears the value of `endColor`. Subsequent reads from it will return its default value.
  public mutating func clearEndColor() {self._endColor = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _startColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
  fileprivate var _endColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
}

/// A Video Component that renders a CSS radial-gradient fill.
public nonisolated struct Ldtx_Workspace_V4_FillRadialGradientComponent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Video Component shown in the Workspace sidebar.
  public var displayName: String = String()

  /// The horizontal coordinate of the gradient center, expressed as a fraction
  /// of the width of the Canvas that renders this Fill, in [0, 1].
  public var centerX: Float = 0

  /// The vertical coordinate of the gradient center, expressed as a fraction
  /// of the height of the Canvas that renders this Fill, in [0, 1].
  public var centerY: Float = 0

  /// The inner radius parameter is in [0, 1] and must be less than
  /// outer_radius.
  public var innerRadius: Float = 0

  /// The outer radius parameter is in [0, 1] and must be greater than
  /// inner_radius.
  public var outerRadius: Float = 0

  /// The color at the inner radius.
  public var innerColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_innerColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_innerColor = newValue}
  }
  /// Returns true if `innerColor` has been explicitly set.
  public var hasInnerColor: Bool {self._innerColor != nil}
  /// Clears the value of `innerColor`. Subsequent reads from it will return its default value.
  public mutating func clearInnerColor() {self._innerColor = nil}

  /// The color at the outer radius.
  public var outerColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_outerColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_outerColor = newValue}
  }
  /// Returns true if `outerColor` has been explicitly set.
  public var hasOuterColor: Bool {self._outerColor != nil}
  /// Clears the value of `outerColor`. Subsequent reads from it will return its default value.
  public mutating func clearOuterColor() {self._outerColor = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _innerColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
  fileprivate var _outerColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
}

/// A Video Component that renders a CSS conic-gradient fill.
public nonisolated struct Ldtx_Workspace_V4_FillConicGradientComponent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Video Component shown in the Workspace sidebar.
  public var displayName: String = String()

  /// The horizontal coordinate of the gradient center, expressed as a fraction
  /// of the width of the Canvas that renders this Fill, in [0, 1].
  public var centerX: Float = 0

  /// The vertical coordinate of the gradient center, expressed as a fraction
  /// of the height of the Canvas that renders this Fill, in [0, 1].
  public var centerY: Float = 0

  /// The gradient start angle in radians.
  public var startAngleRadians: Float = 0

  /// The color at the gradient start angle.
  public var startColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_startColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_startColor = newValue}
  }
  /// Returns true if `startColor` has been explicitly set.
  public var hasStartColor: Bool {self._startColor != nil}
  /// Clears the value of `startColor`. Subsequent reads from it will return its default value.
  public mutating func clearStartColor() {self._startColor = nil}

  /// The color at the gradient end angle.
  public var endColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_endColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_endColor = newValue}
  }
  /// Returns true if `endColor` has been explicitly set.
  public var hasEndColor: Bool {self._endColor != nil}
  /// Clears the value of `endColor`. Subsequent reads from it will return its default value.
  public mutating func clearEndColor() {self._endColor = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _startColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
  fileprivate var _endColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
}

/// A Video Component that applies Video Effects to video from an Input Device.
public nonisolated struct Ldtx_Workspace_V4_VfxSourceComponent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Video Component shown in the Workspace sidebar.
  public var displayName: String = String()

  /// The Video Input Device that provides this VFX Source's input video. This
  /// must not reference a Video Component or an Audio Input Device.
  public var inputDeviceInternalID: UInt64 = 0

  /// The VFX effects applied to the input video, in evaluation order.
  public var effects: [Ldtx_Workspace_V4_VideoEffectWrapper] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A Video Component that renders a test pattern.
public nonisolated struct Ldtx_Workspace_V4_TestPatternComponent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Video Component shown in the Workspace sidebar.
  public var displayName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A Video Component that renders the current date and time.
public nonisolated struct Ldtx_Workspace_V4_ClockComponent: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 {
    get {_storage._internalID}
    set {_uniqueStorage()._internalID = newValue}
  }

  /// The name of this Video Component shown in the Workspace sidebar.
  public var displayName: String {
    get {_storage._displayName}
    set {_uniqueStorage()._displayName = newValue}
  }

  /// The Clock width normalized to the fixed 1920-pixel Landscape Canvas width,
  /// in [0, 1]. This remains the reference for Portrait projection.
  public var width: Float {
    get {_storage._width}
    set {_uniqueStorage()._width = newValue}
  }

  /// The Clock height normalized to the fixed 1080-pixel Landscape Canvas
  /// height, in [0, 1]. This remains the reference for Portrait projection.
  public var height: Float {
    get {_storage._height}
    set {_uniqueStorage()._height = newValue}
  }

  /// Whether the rendered Clock includes the date.
  public var showsDate: Bool {
    get {_storage._showsDate}
    set {_uniqueStorage()._showsDate = newValue}
  }

  /// Whether the rendered time includes seconds.
  public var showsSeconds: Bool {
    get {_storage._showsSeconds}
    set {_uniqueStorage()._showsSeconds = newValue}
  }

  /// Whether the rendered time uses a 24-hour clock.
  public var uses24HourTime: Bool {
    get {_storage._uses24HourTime}
    set {_uniqueStorage()._uses24HourTime = newValue}
  }

  /// The fixed offset from UTC in minutes. When absent, the Clock uses the
  /// system time zone.
  public var utcOffsetMinutes: Int32 {
    get {_storage._utcOffsetMinutes ?? 0}
    set {_uniqueStorage()._utcOffsetMinutes = newValue}
  }
  /// Returns true if `utcOffsetMinutes` has been explicitly set.
  public var hasUtcOffsetMinutes: Bool {_storage._utcOffsetMinutes != nil}
  /// Clears the value of `utcOffsetMinutes`. Subsequent reads from it will return its default value.
  public mutating func clearUtcOffsetMinutes() {_uniqueStorage()._utcOffsetMinutes = nil}

  /// The color of the rendered date and time text.
  public var foregroundColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_storage._foregroundColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_uniqueStorage()._foregroundColor = newValue}
  }
  /// Returns true if `foregroundColor` has been explicitly set.
  public var hasForegroundColor: Bool {_storage._foregroundColor != nil}
  /// Clears the value of `foregroundColor`. Subsequent reads from it will return its default value.
  public mutating func clearForegroundColor() {_uniqueStorage()._foregroundColor = nil}

  /// The background color of this Clock.
  public var backgroundColor: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_storage._backgroundColor ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_uniqueStorage()._backgroundColor = newValue}
  }
  /// Returns true if `backgroundColor` has been explicitly set.
  public var hasBackgroundColor: Bool {_storage._backgroundColor != nil}
  /// Clears the value of `backgroundColor`. Subsequent reads from it will return its default value.
  public mutating func clearBackgroundColor() {_uniqueStorage()._backgroundColor = nil}

  /// The text outlines rendered around the Clock text, in order.
  public var outlines: [Ldtx_Workspace_V4_ClockTextOutline] {
    get {_storage._outlines}
    set {_uniqueStorage()._outlines = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// A text outline rendered by a Clock.
public nonisolated struct Ldtx_Workspace_V4_ClockTextOutline: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The outline thickness in output pixels.
  public var thickness: Float = 0

  /// The color of this outline.
  public var color: Ldtx_Workspace_V4_ExtendedSrgbColor {
    get {_color ?? Ldtx_Workspace_V4_ExtendedSrgbColor()}
    set {_color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  public var hasColor: Bool {self._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  public mutating func clearColor() {self._color = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _color: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
}

/// A color represented in the extended sRGB color space.
public nonisolated struct Ldtx_Workspace_V4_ExtendedSrgbColor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The red component in the extended sRGB color space.
  public var red: Float = 0

  /// The green component in the extended sRGB color space.
  public var green: Float = 0

  /// The blue component in the extended sRGB color space.
  public var blue: Float = 0

  /// The straight alpha component, in the range [0, 1].
  public var alpha: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v4"

nonisolated extension Ldtx_Workspace_V4_VideoComponentWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoComponentWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}solid_color_fill\0\u{3}linear_gradient_fill\0\u{3}radial_gradient_fill\0\u{3}conic_gradient_fill\0\u{3}vfx_source\0\u{1}clock\0\u{3}test_pattern\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Ldtx_Workspace_V4_FillSolidColorComponent?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .solidColorFill(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .solidColorFill(v)
        }
      }()
      case 2: try {
        var v: Ldtx_Workspace_V4_FillLinearGradientComponent?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .linearGradientFill(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .linearGradientFill(v)
        }
      }()
      case 3: try {
        var v: Ldtx_Workspace_V4_FillRadialGradientComponent?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .radialGradientFill(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .radialGradientFill(v)
        }
      }()
      case 4: try {
        var v: Ldtx_Workspace_V4_FillConicGradientComponent?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .conicGradientFill(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .conicGradientFill(v)
        }
      }()
      case 5: try {
        var v: Ldtx_Workspace_V4_VfxSourceComponent?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .vfxSource(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .vfxSource(v)
        }
      }()
      case 6: try {
        var v: Ldtx_Workspace_V4_ClockComponent?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .clock(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .clock(v)
        }
      }()
      case 7: try {
        var v: Ldtx_Workspace_V4_TestPatternComponent?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .testPattern(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .testPattern(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.definition {
    case .solidColorFill?: try {
      guard case .solidColorFill(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .linearGradientFill?: try {
      guard case .linearGradientFill(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .radialGradientFill?: try {
      guard case .radialGradientFill(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .conicGradientFill?: try {
      guard case .conicGradientFill(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .vfxSource?: try {
      guard case .vfxSource(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .clock?: try {
      guard case .clock(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .testPattern?: try {
      guard case .testPattern(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_VideoComponentWrapper, rhs: Ldtx_Workspace_V4_VideoComponentWrapper) -> Bool {
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_FillSolidColorComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FillSolidColorComponent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0\u{1}color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._color) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    try { if let v = self._color {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_FillSolidColorComponent, rhs: Ldtx_Workspace_V4_FillSolidColorComponent) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs._color != rhs._color {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_FillLinearGradientComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FillLinearGradientComponent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0\u{3}start_x\0\u{3}start_y\0\u{3}start_color\0\u{3}end_x\0\u{3}end_y\0\u{3}end_color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.startX) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.startY) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._startColor) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.endX) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self.endY) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._endColor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if self.startX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.startX, fieldNumber: 3)
    }
    if self.startY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.startY, fieldNumber: 4)
    }
    try { if let v = self._startColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.endX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.endX, fieldNumber: 6)
    }
    if self.endY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.endY, fieldNumber: 7)
    }
    try { if let v = self._endColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_FillLinearGradientComponent, rhs: Ldtx_Workspace_V4_FillLinearGradientComponent) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.startX != rhs.startX {return false}
    if lhs.startY != rhs.startY {return false}
    if lhs._startColor != rhs._startColor {return false}
    if lhs.endX != rhs.endX {return false}
    if lhs.endY != rhs.endY {return false}
    if lhs._endColor != rhs._endColor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_FillRadialGradientComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FillRadialGradientComponent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0\u{3}center_x\0\u{3}center_y\0\u{3}inner_radius\0\u{3}outer_radius\0\u{3}inner_color\0\u{3}outer_color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.centerX) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.centerY) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.innerRadius) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.outerRadius) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._innerColor) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._outerColor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if self.centerX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.centerX, fieldNumber: 3)
    }
    if self.centerY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.centerY, fieldNumber: 4)
    }
    if self.innerRadius.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.innerRadius, fieldNumber: 5)
    }
    if self.outerRadius.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.outerRadius, fieldNumber: 6)
    }
    try { if let v = self._innerColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._outerColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_FillRadialGradientComponent, rhs: Ldtx_Workspace_V4_FillRadialGradientComponent) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.centerX != rhs.centerX {return false}
    if lhs.centerY != rhs.centerY {return false}
    if lhs.innerRadius != rhs.innerRadius {return false}
    if lhs.outerRadius != rhs.outerRadius {return false}
    if lhs._innerColor != rhs._innerColor {return false}
    if lhs._outerColor != rhs._outerColor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_FillConicGradientComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FillConicGradientComponent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0\u{3}center_x\0\u{3}center_y\0\u{3}start_angle_radians\0\u{3}start_color\0\u{3}end_color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.centerX) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.centerY) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.startAngleRadians) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._startColor) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._endColor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if self.centerX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.centerX, fieldNumber: 3)
    }
    if self.centerY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.centerY, fieldNumber: 4)
    }
    if self.startAngleRadians.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.startAngleRadians, fieldNumber: 5)
    }
    try { if let v = self._startColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._endColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_FillConicGradientComponent, rhs: Ldtx_Workspace_V4_FillConicGradientComponent) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.centerX != rhs.centerX {return false}
    if lhs.centerY != rhs.centerY {return false}
    if lhs.startAngleRadians != rhs.startAngleRadians {return false}
    if lhs._startColor != rhs._startColor {return false}
    if lhs._endColor != rhs._endColor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_VfxSourceComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VfxSourceComponent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0\u{3}input_device_internal_id\0\u{1}effects\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.inputDeviceInternalID) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.effects) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if self.inputDeviceInternalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputDeviceInternalID, fieldNumber: 3)
    }
    if !self.effects.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.effects, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_VfxSourceComponent, rhs: Ldtx_Workspace_V4_VfxSourceComponent) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.inputDeviceInternalID != rhs.inputDeviceInternalID {return false}
    if lhs.effects != rhs.effects {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_TestPatternComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TestPatternComponent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_TestPatternComponent, rhs: Ldtx_Workspace_V4_TestPatternComponent) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_ClockComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClockComponent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0\u{1}width\0\u{1}height\0\u{3}shows_date\0\u{3}shows_seconds\0\u{3}uses_24_hour_time\0\u{3}utc_offset_minutes\0\u{3}foreground_color\0\u{3}background_color\0\u{1}outlines\0")

  fileprivate class _StorageClass {
    var _internalID: UInt64 = 0
    var _displayName: String = String()
    var _width: Float = 0
    var _height: Float = 0
    var _showsDate: Bool = false
    var _showsSeconds: Bool = false
    var _uses24HourTime: Bool = false
    var _utcOffsetMinutes: Int32? = nil
    var _foregroundColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
    var _backgroundColor: Ldtx_Workspace_V4_ExtendedSrgbColor? = nil
    var _outlines: [Ldtx_Workspace_V4_ClockTextOutline] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _internalID = source._internalID
      _displayName = source._displayName
      _width = source._width
      _height = source._height
      _showsDate = source._showsDate
      _showsSeconds = source._showsSeconds
      _uses24HourTime = source._uses24HourTime
      _utcOffsetMinutes = source._utcOffsetMinutes
      _foregroundColor = source._foregroundColor
      _backgroundColor = source._backgroundColor
      _outlines = source._outlines
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._internalID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._displayName) }()
        case 3: try { try decoder.decodeSingularFloatField(value: &_storage._width) }()
        case 4: try { try decoder.decodeSingularFloatField(value: &_storage._height) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._showsDate) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._showsSeconds) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._uses24HourTime) }()
        case 8: try { try decoder.decodeSingularSInt32Field(value: &_storage._utcOffsetMinutes) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._foregroundColor) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._backgroundColor) }()
        case 11: try { try decoder.decodeRepeatedMessageField(value: &_storage._outlines) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._internalID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._internalID, fieldNumber: 1)
      }
      if !_storage._displayName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._displayName, fieldNumber: 2)
      }
      if _storage._width.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._width, fieldNumber: 3)
      }
      if _storage._height.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._height, fieldNumber: 4)
      }
      if _storage._showsDate != false {
        try visitor.visitSingularBoolField(value: _storage._showsDate, fieldNumber: 5)
      }
      if _storage._showsSeconds != false {
        try visitor.visitSingularBoolField(value: _storage._showsSeconds, fieldNumber: 6)
      }
      if _storage._uses24HourTime != false {
        try visitor.visitSingularBoolField(value: _storage._uses24HourTime, fieldNumber: 7)
      }
      try { if let v = _storage._utcOffsetMinutes {
        try visitor.visitSingularSInt32Field(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._foregroundColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._backgroundColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      if !_storage._outlines.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._outlines, fieldNumber: 11)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_ClockComponent, rhs: Ldtx_Workspace_V4_ClockComponent) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._internalID != rhs_storage._internalID {return false}
        if _storage._displayName != rhs_storage._displayName {return false}
        if _storage._width != rhs_storage._width {return false}
        if _storage._height != rhs_storage._height {return false}
        if _storage._showsDate != rhs_storage._showsDate {return false}
        if _storage._showsSeconds != rhs_storage._showsSeconds {return false}
        if _storage._uses24HourTime != rhs_storage._uses24HourTime {return false}
        if _storage._utcOffsetMinutes != rhs_storage._utcOffsetMinutes {return false}
        if _storage._foregroundColor != rhs_storage._foregroundColor {return false}
        if _storage._backgroundColor != rhs_storage._backgroundColor {return false}
        if _storage._outlines != rhs_storage._outlines {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_ClockTextOutline: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClockTextOutline"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}thickness\0\u{1}color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.thickness) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._color) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.thickness.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.thickness, fieldNumber: 1)
    }
    try { if let v = self._color {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_ClockTextOutline, rhs: Ldtx_Workspace_V4_ClockTextOutline) -> Bool {
    if lhs.thickness != rhs.thickness {return false}
    if lhs._color != rhs._color {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_ExtendedSrgbColor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ExtendedSrgbColor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}red\0\u{1}green\0\u{1}blue\0\u{1}alpha\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.red) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.green) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.blue) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.alpha) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.red.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.red, fieldNumber: 1)
    }
    if self.green.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.green, fieldNumber: 2)
    }
    if self.blue.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.blue, fieldNumber: 3)
    }
    if self.alpha.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.alpha, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_ExtendedSrgbColor, rhs: Ldtx_Workspace_V4_ExtendedSrgbColor) -> Bool {
    if lhs.red != rhs.red {return false}
    if lhs.green != rhs.green {return false}
    if lhs.blue != rhs.blue {return false}
    if lhs.alpha != rhs.alpha {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
