// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace_v4_input_device.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

/// Version 4 Workspace Input Device definitions.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Wraps one concrete Input Device definition.
public nonisolated struct Ldtx_Workspace_V4_InputDeviceWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var definition: Ldtx_Workspace_V4_InputDeviceWrapper.OneOf_Definition? = nil

  /// The Video Input Device definition. Mutually exclusive with the other
  /// fields.
  public var videoDevice: Ldtx_Workspace_V4_VideoInputDevice {
    get {
      if case .videoDevice(let v)? = definition {return v}
      return Ldtx_Workspace_V4_VideoInputDevice()
    }
    set {definition = .videoDevice(newValue)}
  }

  /// The Audio Input Device definition. Mutually exclusive with the other
  /// fields.
  public var audioDevice: Ldtx_Workspace_V4_AudioInputDevice {
    get {
      if case .audioDevice(let v)? = definition {return v}
      return Ldtx_Workspace_V4_AudioInputDevice()
    }
    set {definition = .audioDevice(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    /// The Video Input Device definition. Mutually exclusive with the other
    /// fields.
    case videoDevice(Ldtx_Workspace_V4_VideoInputDevice)
    /// The Audio Input Device definition. Mutually exclusive with the other
    /// fields.
    case audioDevice(Ldtx_Workspace_V4_AudioInputDevice)

  }

  public init() {}
}

/// A video Input Device available in a Workspace.
public nonisolated struct Ldtx_Workspace_V4_VideoInputDevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Input Device shown in the Workspace sidebar.
  public var displayName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// An audio Input Device available in a Workspace.
public nonisolated struct Ldtx_Workspace_V4_AudioInputDevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Workspace-local identifier for this entity. Its most significant bit
  /// is zero; bits 62 through 15 encode milliseconds since the Unix epoch,
  /// and bits 14 through 0 are uniformly random.
  public var internalID: UInt64 = 0

  /// The name of this Input Device shown in the Workspace sidebar.
  public var displayName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v4"

nonisolated extension Ldtx_Workspace_V4_InputDeviceWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputDeviceWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}video_device\0\u{3}audio_device\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Ldtx_Workspace_V4_VideoInputDevice?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .videoDevice(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .videoDevice(v)
        }
      }()
      case 2: try {
        var v: Ldtx_Workspace_V4_AudioInputDevice?
        var hadOneofValue = false
        if let current = self.definition {
          hadOneofValue = true
          if case .audioDevice(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.definition = .audioDevice(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.definition {
    case .videoDevice?: try {
      guard case .videoDevice(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .audioDevice?: try {
      guard case .audioDevice(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_InputDeviceWrapper, rhs: Ldtx_Workspace_V4_InputDeviceWrapper) -> Bool {
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_VideoInputDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoInputDevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_VideoInputDevice, rhs: Ldtx_Workspace_V4_VideoInputDevice) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_AudioInputDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AudioInputDevice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}internal_id\0\u{3}display_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.internalID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.internalID != 0 {
      try visitor.visitSingularUInt64Field(value: self.internalID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_AudioInputDevice, rhs: Ldtx_Workspace_V4_AudioInputDevice) -> Bool {
    if lhs.internalID != rhs.internalID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
